export const chessConstants = {
  INITIAL_FEN_POSITION: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  DEFAULT_TIME_CONTROL: '5+0',
  RATING_INCREMENT: 20,
  DRAW_OFFER_TIMEOUT: 30,
  MIN_ELO_RATING: 100,
  MAX_ELO_RATING: 3500,
}